/**
 * Supabase Database Types
 *
 * This file will be auto-generated by Supabase CLI:
 * npx supabase gen types typescript --project-id [project-id] > src/api/database.types.ts
 *
 * For now, using a placeholder type.
 * Once Supabase is set up, regenerate this file for full type safety.
 */

export interface Database {
  public: {
    Tables: {
      heritage_sites: {
        Row: {
          id: string;
          name: string;
          name_arabic: string | null;
          type: string;
          year_built: string;
          year_built_islamic: string | null;
          coordinates: unknown; // PostGIS geography type
          status: string;
          date_destroyed: string | null;
          date_destroyed_islamic: string | null;
          description: string;
          historical_significance: string;
          cultural_value: string;
          verified_by: string[];
          images: unknown | null; // JSONB
          sources: unknown[]; // JSONB array
          unesco_listed: boolean | null;
          artifact_count: number | null;
          is_unique: boolean | null;
          religious_significance: boolean | null;
          community_gathering_place: boolean | null;
          historical_events: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['heritage_sites']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['heritage_sites']['Insert']>;
      };
    };
  };
}
