/**
 * Supabase Database Types
 *
 * This file will be auto-generated by Supabase CLI:
 * npx supabase gen types typescript --project-id [project-id] > src/api/database.types.ts
 *
 * For now, using a placeholder type.
 * Once Supabase is set up, regenerate this file for full type safety.
 */

export interface Database {
  public: {
    Tables: {
      heritage_sites: {
        Row: {
          id: string;
          name: string;
          name_arabic: string | null;
          type: string;
          year_built: string;
          year_built_islamic: string | null;
          coordinates: { coordinates: [number, number] }; // PostGIS geography type (GeoJSON)
          status: string;
          date_destroyed: string | null;
          date_destroyed_islamic: string | null;
          description: string;
          historical_significance: string;
          cultural_value: string;
          verified_by: string[];
          images: Record<string, unknown>[] | null; // JSONB array
          sources: Record<string, unknown>[]; // JSONB array
          unesco_listed: boolean | null;
          artifact_count: number | null;
          is_unique: boolean | null;
          religious_significance: boolean | null;
          community_gathering_place: boolean | null;
          historical_events: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          name_arabic?: string | null;
          type: string;
          year_built: string;
          year_built_islamic?: string | null;
          coordinates: string; // WKT format for insert
          status: string;
          date_destroyed?: string | null;
          date_destroyed_islamic?: string | null;
          description: string;
          historical_significance: string;
          cultural_value: string;
          verified_by: string[];
          images?: Record<string, unknown>[] | null;
          sources: Record<string, unknown>[];
          unesco_listed?: boolean | null;
          artifact_count?: number | null;
          is_unique?: boolean | null;
          religious_significance?: boolean | null;
          community_gathering_place?: boolean | null;
          historical_events?: string[] | null;
        };
        Update: {
          name?: string;
          name_arabic?: string | null;
          type?: string;
          year_built?: string;
          year_built_islamic?: string | null;
          coordinates?: string;
          status?: string;
          date_destroyed?: string | null;
          date_destroyed_islamic?: string | null;
          description?: string;
          historical_significance?: string;
          cultural_value?: string;
          verified_by?: string[];
          images?: Record<string, unknown>[] | null;
          sources?: Record<string, unknown>[];
          unesco_listed?: boolean | null;
          artifact_count?: number | null;
          is_unique?: boolean | null;
          religious_significance?: boolean | null;
          community_gathering_place?: boolean | null;
          historical_events?: string[] | null;
        };
      };
    };
    Functions: {
      sites_near_point: {
        Args: {
          lat: number;
          lng: number;
          radius_km: number;
        };
        Returns: Database['public']['Tables']['heritage_sites']['Row'][];
      };
    };
  };
}
